name: Build
on:
  push: {branches: [main], tags: v*}
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup Earthly
      uses: earthly/actions-setup@v1
      with:
        version: "latest"
        github-token: ${{ github.token }}
    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Build Worker
      env: 
        GLOBAL_CACHE_IMAGE: ghcr.io/${{github.repository}}/build-cache
      run: earthly --max-remote-cache --use-inline-cache --save-inline-cache --strict --push --remote-cache=ghcr.io/${{github.repository}}/build-cache:cache +worker
    - run: ls -lavR /tmp/earthly
    - name: Create Tarball
      run: tar --directory=_build -cvf worker.tar.xz worker
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: worker.tar.xz
